# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from Collections import users
import admin, user

class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        # keep a reference to the dialog so we can show it again after logout
        self.LoginDialog = LoginDialog
        LoginDialog.resize(400, 220)
        self.verticalLayout = QtWidgets.QVBoxLayout(LoginDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=LoginDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.usernameLabel = QtWidgets.QLabel(parent=LoginDialog)
        self.usernameLabel.setObjectName("usernameLabel")
        self.gridLayout.addWidget(self.usernameLabel, 0, 0, 1, 1)
        self.usernameLineEdit = QtWidgets.QLineEdit(parent=LoginDialog)
        self.usernameLineEdit.setClearButtonEnabled(True)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.gridLayout.addWidget(self.usernameLineEdit, 0, 1, 1, 1)
        self.passwordLabel = QtWidgets.QLabel(parent=LoginDialog)
        self.passwordLabel.setObjectName("passwordLabel")
        self.gridLayout.addWidget(self.passwordLabel, 1, 0, 1, 1)
        self.passwordLineEdit = QtWidgets.QLineEdit(parent=LoginDialog)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordLineEdit.setClearButtonEnabled(True)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.gridLayout.addWidget(self.passwordLineEdit, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.statusLabel = QtWidgets.QLabel(parent=LoginDialog)
        self.statusLabel.setMinimumSize(QtCore.QSize(0, 18))
        self.statusLabel.setStyleSheet("color: #b00020;")
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout.addWidget(self.statusLabel)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=LoginDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "Login - BookFlow"))
        self.titleLabel.setText(_translate("LoginDialog", "BookFlow Login"))
        self.usernameLabel.setText(_translate("LoginDialog", "Username:"))
        self.usernameLineEdit.setPlaceholderText(_translate("LoginDialog", "Enter username"))
        self.passwordLabel.setText(_translate("LoginDialog", "Password:"))
        self.passwordLineEdit.setPlaceholderText(_translate("LoginDialog", "Enter password"))
        self.buttonBox.accepted.connect(self.login)
        self.buttonBox.rejected.connect(exit)

    def login(self):
        try:
            username = self.usernameLineEdit.text()
            password = self.passwordLineEdit.text()
            u = users.verify_password(username, password)
            if u.get("status") == "disabled":
                raise Exception("This user is disabled")
            role = u.get("role")
            if role == "Admin":
                self.LoginDialog.hide()
                self.admin_main = QtWidgets.QMainWindow()
                self.admin_ui = admin.Ui_MainWindow(username, u.get("name"))
                self.admin_ui.setupUi(self.admin_main)

                def _logout():
                    try:
                        self.admin_main.close()
                    except Exception:
                        pass
                    self.passwordLineEdit.clear()
                    self.usernameLineEdit.clear()
                    self.statusLabel.setText("")
                    self.LoginDialog.show()

                try:
                    self.admin_ui.actionLogin.triggered.connect(_logout)
                except Exception:
                    pass

                self.admin_main.show()
            elif role == "User":
                self.LoginDialog.hide()
                self.user_main = QtWidgets.QMainWindow()
                self.user_ui = user.Ui_MainWindow(username, u.get("name"))
                self.user_ui.setupUi(self.user_main)

                def _logout():
                    try:
                        self.user_main.close()
                    except Exception:
                        pass
                    self.passwordLineEdit.clear()
                    self.usernameLineEdit.clear()
                    self.statusLabel.setText("")
                    self.LoginDialog.show()

                try:
                    self.user_ui.actionLogin.triggered.connect(_logout)
                except:
                    pass
                self.user_main.show()
        except Exception as e:
            self.statusLabel.setText(str(e))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginDialog = QtWidgets.QDialog()
    ui = Ui_LoginDialog()
    ui.setupUi(LoginDialog)
    LoginDialog.show()
    sys.exit(app.exec())
